spring.datasource.url=jdbc:postgresql://localhost:5432/paystream
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
razorpay.key.id=your_key_id_here
razorpay.key.secret=your_key_secret_here
spring.data.redis.host=localhost
spring.data.redis.port=6379
paypal.client.id=${PAYPAL_CLIENT_ID}
paypal.client.secret=${PAYPAL_CLIENT_SECRET}
cashfree.client.id=${CASHFREE_CLIENT_ID}
cashfree.client.secret=${CASHFREE_CLIENT_SECRET}