spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paystream}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
paypal.client.id=${PAYPAL_CLIENT_ID}
paypal.client.secret=${PAYPAL_CLIENT_SECRET}
cashfree.client.id=${CASHFREE_CLIENT_ID}
cashfree.client.secret=${CASHFREE_CLIENT_SECRET}
circuit.breaker.consecutive.threshold=3
circuit.breaker.sla=0.95
circuit.breaker.tolerance=0.10
circuit.breaker.min.requests.per.minute=10
cors.allowed.origins=http://localhost:4200